### ISSUE TITLE
Write up Lesson Plan for Week 4 - Narrowing and Structural Typing

### ISSUE THREAD

**Issue by dskamiotis** [guardian/typescript-school#7]
### Narrowing and Structural Typing

See [here](https://docs.google.com/presentation/d/150b7CKHA-s9NQ05GWXzrgEAk2lyuikbO2la6TklFaEw/edit#slide=id.g256b012de15_0_26) for ref to handbook and slideshow

```[tasklist]
### Tasks
- [ ] Narrowing example similar to TS handbook
- [ ] Structural typing / “duck” analogy / contrast with nominal typing
- [ ] Discriminated unions
- [ ] Type predicates and examples in @guardian/libs, but not assertion functions
- [ ] Exercises
- [ ] Keep type casting out
```
